# version: '3.8'

# services:
#   app:
#     build: .
#     ports:
#       - "3001:3001"
#     environment:
#       - NODE_ENV=production
#       - DB_NAME=/data/travel_tales.db
#       - JWT_SECRET=your_secure_jwt_secret
#       - COUNTRIES_API=https://restcountries.com/v3.1
#     volumes:
#       - ./db:/data
#     depends_on:
#       - db
#     networks:
#       - travel-tales-net

#   db:
#     image: sqlitecloud/sqlitecloud # Lightweight SQLite with network support
#     volumes:
#       - ./db:/data
#     networks:
#       - travel-tales-net

# networks:
#   travel-tales-net:
#     driver: bridge


# version: '3.8'
# services:
#   app:  # Backend service
#     build: 
#       context: ./traveltales-backend
#       dockerfile: Dockerfile
#     ports:
#       - "3001:3001"
#     environment:
#       - NODE_ENV=production
#       - DB_NAME=/data/travel_tales.db
#     volumes:
#       - ./traveltales-backend/db:/data

#   frontend:
#     build:
#       context: ./traveltales-frontend
#       dockerfile: Dockerfile
#     ports:
#       - "3000:80"
#     depends_on:
#       - app


version: '3.8'

services:
  backend:
    build: ./traveltales-backend
    container_name: traveltales-backend
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_NAME=travel_tales.db
      - JWT_SECRET=your_strong_secret_here 
      - JWT_EXPIRES_IN=1h 
      - COUNTRIES_API=https://restcountries.com/v3.1
    volumes:
      - ./traveltales-backend/db:/data
    user: "node"  # Run as non-root user
    restart: unless-stopped

  frontend:
    build: ./traveltales-frontend
    container_name: traveltales-frontend
    ports:
      - "3000:80"
    depends_on:
      backend:
        condition: service_healthy