version: '3.8'

services:
  app:
    build: .
    ports:
      - "3001:3001"
    environment:
      - NODE_ENV=production
      - DB_NAME=/data/travel_tales.db
      - JWT_SECRET=your_secure_jwt_secret
      - COUNTRIES_API=https://restcountries.com/v3.1
    volumes:
      - ./db:/data
    depends_on:
      - db
    networks:
      - travel-tales-net

  db:
    image: sqlitecloud/sqlitecloud # Lightweight SQLite with network support
    volumes:
      - ./db:/data
    networks:
      - travel-tales-net

networks:
  travel-tales-net:
    driver: bridge